# Generated by Django 5.0.6 on 2025-03-13 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('caballos', '0001_initial'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('Pony', 'Pony'), ('Escuelita', 'Escuelita'), ('Escuela', 'Escuela')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='clases.categoria')),
                ('id_profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='profesores.profesor')),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='clases.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='alumnos.alumno')),
                ('id_caballo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='caballos.caballo')),
                ('id_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='clases.clase')),
            ],
        ),
    ]
