# Generated by Django 5.0.6 on 2025-03-13 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caballos', '0002_disciplina_remove_caballo_disciplinas_and_more'),
        ('clases', '0001_initial'),
        ('competencias', '0003_alter_evento_id_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='id_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='caballos.disciplina'),
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
