# Generated by Django 5.0.6 on 2025-03-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_alter_clase_id_disciplina_delete_disciplina'),
    ]

    operations = [
    ]
