# Generated by Django 5.0.6 on 2025-03-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_initial_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
