# Generated by Django 5.0.6 on 2025-03-14 00:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alter_alumno_usuario'),
        ('caballos', '0007_alter_caballo_disciplinas'),
        ('clases', '0004_alter_categoria_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='fecha',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clase',
            name='id_alumnos',
            field=models.ManyToManyField(related_name='clases', to='alumnos.alumno'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='id_caballo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='caballos.caballo'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('Pony', 'Pony'), ('Escuelita', 'Escuelita'), ('Escuela', 'Escuela')], max_length=100),
        ),
    ]
