# Generated by Django 5.0.6 on 2025-03-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0005_remove_clase_fecha_asistencia_fecha_clase_id_alumnos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
