# Generated by Django 5.0.6 on 2025-03-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0006_alter_clase_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='id_alumnos',
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
