# Generated by Django 5.0.6 on 2025-03-21 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.TextField(blank=True, choices=[('cuota', 'Cuota'), ('inscripcion', 'Inscripcion')], max_length=50, null=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montos', to='clases.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_alumno', to='alumnos.alumno')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_detalle', to='clases.clase')),
                ('monto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='cuotas.monto')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=2)),
            ],
            options={
                'unique_together': {('anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencida', 'Vencida'), ('proximo', 'Próximo'), ('cancelada', 'Cancelada')], default='proximo', max_length=10)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas_alumno', to='alumnos.alumnoclase')),
                ('detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_detalle', to='alumnos.alumnoclase')),
                ('id_periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='cuotas.periodo')),
            ],
        ),
    ]
