# Generated by Django 5.0.6 on 2025-03-13 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('cajas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=2)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='alumnos.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='CuotasPorPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cuotas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_por_pago', to='cuotas.cuota')),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_por_pago', to='cajas.pago')),
            ],
        ),
    ]
