# Generated by Django 5.0.6 on 2025-03-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0002_initial'),
        ('cuotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='pagos',
            field=models.ManyToManyField(related_name='cuotas', to='cajas.pago'),
        ),
        migrations.DeleteModel(
            name='CuotasPorPago',
        ),
    ]
