# Generated by Django 5.0.6 on 2025-03-13 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0002_cuota_pagos_delete_cuotasporpago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='pagos',
        ),
    ]
