# Generated by Django 5.0.6 on 2025-03-13 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0003_remove_cuota_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='vencimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
