# Generated by Django 5.0.6 on 2025-03-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0004_cuota_vencimiento_alter_cuota_fecha_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuota',
            old_name='vencimiento',
            new_name='fecha_vencimiento',
        ),
    ]
