# Generated by Django 5.0.6 on 2025-03-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0005_rename_vencimiento_cuota_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='fecha_vencimiento',
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fecha_pago',
            field=models.DateTimeField(),
        ),
    ]
