# Generated by Django 5.0.6 on 2025-03-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0006_remove_cuota_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencida', 'Vencida')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
