# Generated by Django 5.0.6 on 2025-03-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0007_cuota_estado_alter_cuota_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
