# Generated by Django 5.0.6 on 2025-03-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0008_cuota_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
