# Generated by Django 5.0.6 on 2025-03-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0009_alter_cuota_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
