# Generated by Django 5.0.6 on 2025-03-21 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caballo',
            fields=[
                ('id_caballo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CaballoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caballo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caballos.caballo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.disciplina')),
            ],
        ),
    ]
