# Generated by Django 5.0.6 on 2025-03-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caballo',
            fields=[
                ('id_caballo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('disciplinas', models.ManyToManyField(to='clases.disciplina')),
            ],
        ),
    ]
