# Generated by Django 5.0.6 on 2025-03-13 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caballos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='caballo',
            name='disciplinas',
        ),
        migrations.CreateModel(
            name='CaballosPorDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caballo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caballos.caballo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caballos.disciplina')),
            ],
        ),
    ]
