# Generated by Django 5.0.6 on 2025-03-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caballos', '0002_disciplina_remove_caballo_disciplinas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caballo',
            name='disciplinas',
            field=models.ManyToManyField(to='caballos.disciplina'),
        ),
        migrations.DeleteModel(
            name='CaballosPorDisciplina',
        ),
    ]
