# Generated by Django 5.0.6 on 2025-03-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caballos', '0003_caballo_disciplinas_delete_caballospordisciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caballo',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, to='caballos.disciplina'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nombre',
            field=models.CharField(choices=[('SALTO', 'Salto de Tambores'), ('CARRERA', 'Carrera')], max_length=100),
        ),
    ]
