# Generated by Django 5.0.6 on 2025-03-13 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caballos', '0004_alter_caballo_disciplinas_alter_disciplina_nombre'),
    ]

    operations = [
    ]
