# Generated by Django 5.0.6 on 2025-03-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caballos', '0006_alter_disciplina_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caballo',
            name='disciplinas',
            field=models.ManyToManyField(to='caballos.disciplina'),
        ),
    ]
