# Generated by Django 5.0.6 on 2025-03-13 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('caballos', '0001_initial'),
        ('competencias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inscripciones',
            new_name='Inscripcion',
        ),
    ]
