# Generated by Django 5.0.6 on 2025-03-13 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caballos', '0002_disciplina_remove_caballo_disciplinas_and_more'),
        ('competencias', '0002_rename_inscripciones_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='id_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='caballos.disciplina'),
        ),
    ]
