# Generated by Django 5.0.6 on 2025-03-16 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuotas', '__first__'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('egresos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Cerrada', max_length=50)),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_apertura', to='usuarios.usuario')),
                ('usuario_cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cierre', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pagos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medio_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Crédito', 'Crédito'), ('Débito', 'Débito'), ('Transferencia', 'Transferencia'), ('Billetera Virtual', 'Billetera Virtual')], max_length=50)),
                ('cuotas', models.ManyToManyField(to='cuotas.cuota')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_movimientos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_y_hora', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('id_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='cajas.caja')),
                ('id_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='cajas.pago')),
            ],
        ),
    ]
