# Generated by Django 5.0.6 on 2025-03-13 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cajas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='usuario_apertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_apertura', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='caja',
            name='usuario_cierre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cierre', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='id_caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='cajas.caja'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='id_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='cajas.pago'),
        ),
    ]
