# Generated by Django 5.0.6 on 2025-03-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0002_initial'),
        ('cuotas', '0003_remove_cuota_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cuotas',
            field=models.ManyToManyField(to='cuotas.cuota'),
        ),
    ]
