# Generated by Django 5.0.6 on 2025-03-14 16:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alter_alumno_usuario'),
        ('caballos', '0007_alter_caballo_disciplinas'),
        ('clases', '0007_remove_clase_id_alumnos_delete_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='id_clases',
            field=models.ManyToManyField(related_name='clases', to='clases.clase'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='alumnos.alumno')),
                ('id_caballo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='caballos.caballo')),
                ('id_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='clases.clase')),
            ],
        ),
    ]
