# Generated by Django 5.0.6 on 2025-03-14 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_alumno_id_clases_asistencia'),
        ('clases', '0007_remove_clase_id_alumnos_delete_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='id_categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='clases.categoria'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id_clases',
            field=models.ManyToManyField(related_name='alumnos', to='clases.clase'),
        ),
    ]
