# Generated by Django 5.0.6 on 2025-03-14 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_alumno_id_categoria_alter_alumno_id_clases'),
        ('clases', '0007_remove_clase_id_alumnos_delete_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='id_categoria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='clases.categoria'),
        ),
    ]
