# Generated by Django 5.0.6 on 2025-03-15 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_alter_alumno_id_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id_clases',
        ),
    ]
